prgrms-fe-devcourse/FEDC5_Owhat_Byunghyun

- .prettierrc
- #8
- prettier의 eol 옵션을 `lf`로 변경합니다.
- prettier에서 작업할 때 기본 값으로 `lf`를 권장하고 있기 때문입니다!
- 이에 맞게 기존 파일들의 eol을 변경하여 업로드 합니다.
- 추가로 세팅할 내용
- window만
- `git config core.autocrlf true` -> git이 line ending을 처리하는 방식을 결정합니다. core.autocrlf true로 하시면 저장소에서 가져올 때 CRLF로 가져오고, 저장소로 보낼 때는 LF로 보냅니다.
- mac, linux만
- `git config --global core.autocrlf input` eol을 lf만 사용하도록 합니다.
- [git eol 변경](https://www.lesstif.com/gitbook/git-crlf-20776404.html)
> fix: eol을 lf로 제한

- src/stories/Text.stories.tsx
- #13 
- Text.stories.tsx의 meta title 경로를 수정하였습니다.
> fix: Text 스토리북 meta title 수정

- src/components/common/Textarea/index.tsx
- src/stories/Textarea.stories.tsx
- #9 
- `size`, `placeholder`, `required`, `disabled` props를 받습니다.
- `size`는 `sm`, `lg`로 구분되며 구분 기준은 다음과 같습니다.
- `sm`: 댓글 입력, 채팅 메시지 입력과 같이 `height`가 작은 `textarea`로, 텍스트 길이에 따라 `height`가 늘어나지만 일정 길이 (약 6줄) 이상일 땐 더이상 늘어나지 않는다.
- `lg`: 게시물 입력과 같이 `height`가 일정 길이까지만 늘어나지 않고 화면에서 보이는 만큼 늘어난다.
- storybook에서는 잘 보이게 하기 위해 배경색을 넣었습니다. 보통 배경색 없이 사용될 것으로 예상됩니다.
- 따로 `variants` 등록할 부분이 없다고 생각해서 `cva`를 사용하지 않았는데 다른 의견이 있다면 말해주세요!
- 기본 스타일을 지정하다 보니 좀 많아진 것 같은데.. 이렇게 작성해도 괜찮은 걸까요?
- `size="sm"`일 때 사용되는 최대 높이(`145`)를 상수화(예 - `const MAX_HEIGHT_VALUE = 145`)하는 것이 좋을까요? 의미를 파악하기 힘든 매직 넘버가 되는 것 같아 고민입니다!
> feat: Textarea 컴포넌트 구현

- .github/workflows/chromatic.yaml
- .prettierrc
- package-lock.json
- package.json
- src/common/components/Group/Group.variants.ts
- src/common/components/Group/index.tsx
- src/stories/Group.stories.tsx
- close #17
- 스토리북 배포 ci/cd 구축
- chromatic을 통해 스토리북을 배포합니다.
- chromatic을 이용한 이유는 스토리북 관리자가 만든 배포 서비스이므로 연동하기가 쉽고, 컴포넌트 미리보기, 빌드 과정 등을 최적화 하여 제공하기 때문입니다.
- 빌드가 완료 되면 PR 메시지로 스토리북 배포 url을 자동으로 작성해줍니다.
- Group 컴포넌트 작성
- Group 컴포넌트는 다음과 같은 일을 할 수 있습니다.
- 가로, 세로 방향 선택
- 가로 정렬, 세로 정렬 선택
- 부모 요소 최대 너비에 맞게 모든 자식 요소의 크기를 strech
- 자식 요소들 간의 간격 조정
- wrapping 가능 여부 설정
> feat: Group 컴포넌트 생성

- src/common/components/ExtraInfo/ExtraInfo.variants.ts
- src/common/components/ExtraInfo/index.tsx
- src/stories/ExtraInfo.stories.tsx
- close #45 
- 더미데이터를 만들어서 데이터가 모두 잘 출력되는지 확인합니다.
- map 또는 단일 문자열로 제작할 수 있도록 합니다.
- map인 경우에는 마지막 칸에 '・' 기호가 안 붙도록 합니다.
사용 예시)
```
<ExtraInfo>
<span>게시물 {user.posts.length}</span>
<span>팔로워 {user.followers.length}</span>
<span>팔로잉 {user.following.length}</span> 
</ExtraInfo>
```
> feat: extrainfo 컴포넌트 구현

- src/common/components/Text/Text.variants.ts
- src/common/components/Text/index.tsx
- src/stories/Text.stories.tsx
- close #28 
- 배경 색깔이나 border radius를 상위 컴포넌트에서 자유롭게 설정할 수 있도록 props를 변경합니다.
- stories의 color variants를 제거합니다.
- fontSize => size로 수정합니다.
- TextVariants => textVariants로 수정 (컴포넌트가 아니므로 케이스 변경)
- div, span, p 태그 중 변경할 수 있습니다.
- 폰트 패밀리를 변경할 수 있습니다. (isLogo: true 시 Logo 폰트로 변경)
- text story Obj 명칭을 다른 story Default obj와 이름을 통일시켰습니다.
> Fix: text component 수정

- src/common/components/Button/Button.variants.ts
- src/common/components/Button/index.tsx
- src/stories/Button.stories.tsx
- close #24 
- Loading 컴포넌트를 활용해 props로 loading값이 true가 되면 loading 컴포넌트 출력
- Lodiang 컴포넌트 출력시 버튼의 크기가 변하는 문제 해결
- hover시 opacity로 버튼효과 추가 - transition 적용
- fullwidth 기능구현
- Icon 컴포넌트를  Button요소에 출력 가능
- Props로 border 값을 설정해서 false면 border를 없애주는 기능 구현
타입 명시가 없다면 기본적으로 'submit' 처리가 되며 'submit'은 새로고침을 하게 한다.
[버튼에 타입을 쓰는 이유 (button type="button")](https://nykim.work/96)
https://github.com/prgrms-fe-devcourse/FEDC5_Owhat_Byunghyun/assets/90139306/18540597-5788-47e8-8ace-72191389b89f
추후 현재 폰트 문제 해결
> feat: Button 컴포넌트 구현

- src/common/components/Upload/index.tsx
- src/stories/Upload.stories.tsx
- close #42 
- Image Uploader를 구현했습니다.
- input type file을 이용했습니다.
- onChange 이벤트가 발생하면 사용자가 선택한 파일을 가져와서 base64 형식으로 인코딩합니다.
- 자식 컴포넌트는 `string` 타입의 src 주소, `File` 타입인 file을 각각 넘겨 받을 수 있습니다.
> feat: Image Upload 컴포넌트 생성

- src/common/components/Button/Button.variants.ts
- src/common/components/Button/index.tsx
- src/stories/Button.stories.tsx
- close #66 
text-size와 text-color를 적용하고 twmerge를 사용했을 때 실제로는 하나의 속성만 적용되는 문제가 있었다.
이는 Tailwind의 twmerge의 문제로 나타났고,
stackoverflow에서 twmerge 개발자의 답변으로 "공식 문서의 예시를 참고하여 커스텀을 추가"하거나, "상수로 관리해서 tailwind에서 정의한 기본 속성 활용하기의 두 가지 방법"을 추천했다.
나는 button에서 스타일을 적용하고 button안의 span이 상속받고 있던 상황이어서 
twmerge에서 tailwind에 자식선택자를 이용해 해결했다.
하지만 그렇게 한다면 button에 적용했던 hover와 같은 text-color를 바꾸는 코드가 먹히지 않게 되었다.
왜냐하면 자식선택자로 span의 색상을 고정했기 때문이다.
그래서 cva를 따로 만들어서 button과 span의 cn을 분리해줬다.
[참고 링크](
https://velog.io/@doggopawer/tailwind-%EC%A4%91%EC%B2%A9-%ED%81%B4%EB%9E%98%EC%8A%A4-%EC%98%A4%EB%A5%98)
> refactor: Button 컴포넌트 스타일 수정 및 twmerge 문제 수정

- src/common/components/Text/Text.variants.ts
- src/styles/global.css
- close #78 
- global.css의 전체 선택자에서 'text-black' 삭제
- text 컴포넌트 기본값으로 text-inherit 추가
> fix: text 컴포넌트에 text-inherit 추가, global.css의 text-black 제거

- src/common/components/Button/Button.variants.ts
- src/common/components/Button/index.tsx
- close #82 
- fullwidth를 적용했을 때 버튼안의 요소가 가운데 정렬되지않는 문제 해결
-  flex를 주고 justify-center로 통일함, 그리고 로딩 요소가 나오면 children 콘텐츠는 invisible : visible로 변경
- 만약 버튼의 type이 state로 인해서 바뀌는 로직이 있다면 버튼이 border값으로 인해 크기가 통일되지않은 문제를 모든 button type에 border를 주고, border의 색상을 transparent로 적용함
> fix: button fullWidth 기능 수정 및 스타일 수정

- src/common/components/Badge/Badge.variants.ts
- src/common/components/Badge/index.tsx
- src/stories/Badge.stories.tsx
- close #63 
- 아바타와 아이콘에 쓰일 badge 컴포넌트 구현
- online, offline, alarm으로 타입은 필수로 받는다.
- online/offline은 isActive값과 무관하게 작동한다. (login상태라면 online, 아니라면 offline으로 출력함)
- alarm은 isActive값에 따라 나타나거나 사라진다. ( 알림의 seen값이 하나라도 있을 경우를 위해)
- top-right, top-left, bottom-left, bottom-right로 원하는 위치에 출력할 수 있음
- badge의 사이즈를 받을 수 있음 (xsmall, small, medium, large, xlarge)
- 사이즈가 달라지면 알림을 원하는 요소와 멀어지게 되는데 이를 위해 translate를 원하는 대로 조정할 수 있게함
- translateX와 translateY를 1~11의 값으로 조정이 가능함
> feat: Badge 컴포넌트 구현

- src/common/components/Avatar/Avatar.varients.ts
- src/common/components/Avatar/index.tsx
- src/stories/Avatar.stories.tsx
- close #67 
- Avatar 컴포넌트 border-solid 적용으로 인한 간격 문제 해결
- Avatar 컴포넌트에서는 Image 컴포넌트의 요소가 드래그 안되게 함
- Avatar 컴포넌트 스타일 수정
현재 로컬에서는 default image가 정상적으로 보이는데
CI/CD로 배포된 링크에서는 default image가 안보이는 현상
**로컬**
**배포**
> refactor: Avatar 컴포넌트 스타일 수정 및 드래그 방지 추가

- index.html
- src/App.tsx
- src/common/components/Group/Group.variants.ts
- src/common/components/Header/index.tsx
- src/common/components/Layout/index.tsx
- src/common/components/Logo/index.tsx
- src/common/hooks/useLayout.ts
- src/stories/Group.stories.tsx
- src/stories/Layout.stories.tsx
- close #71 
- Header 컴포넌트를 생성했습니다.
- Page Layout 컴포넌트를 생성했습니다. 해당 컴포넌트는 다음과 같은 역할을 할 수 있습니다.
- 현재 페이지의 document title을 지정합니다. 
- 페이지의 헤더 컴포넌트에 title, left, right 컴포넌트를 지정할 수 있습니다.
- Page Layout을 변경하기 위해서는 다음과 같이 작성할 수 있습니다.
```tsx
// home page
const HomePage = () => {
const { changeMeta } = useLayout();
useEffect(() => {
changeMeta({
left: null,
right: <button>완료</button>,
});
}, []);
return <section>home</section>
}
```
- 걱정되는 부분은 현재 페이지에 최초 진입했을 때 한 번만 changeMeta 함수를 호출해주면 됩니다. 그래서 useEffect를 사용했는데, 의존성 배열에 changeMeta 함수를 넣으라는 warning이 계속 발생합니다. 그래서 넣어주면 오히려 useEffect에서 setState 함수를 실행하지 말라는 에러가 발생하고 무한 리렌더링이 발생합니다. 이걸 해결하기 위해서는 useEffect를 사용하라는 모순이 발생해서 일단은 빈 의존성 배열을 사용했습니다. 이 부분에 대해서는 나중에 더 알아보면 좋을 것 같습니다!
> feat: Page Layout 컴포넌트 생성

- src/common/components/Button/Button.variants.ts
- src/common/components/Button/index.tsx
- close #85 
- disabled 스타일 변경
- span태그 사용 및 폰트로 인한 폰트 아래 여백 제거
> refactor: Button component 스타일 변경

- src/common/components/UserInfo/index.tsx
- src/stories/UserInfo.stories.tsx
- close #106 
- userinfo 컴포넌트에 ismypage props 추가
- ismypage일 경우 페이지 이동 막기
- 아바타와 정보 사이 간격 sm => md로 수정
- storybook id args 변경
#105
> fix: userinfo 컴포넌트와 스토리북 수정

- src/common/components/Carousel/index.tsx
- src/common/components/Carousel/useDragScroll.ts
- src/stories/Carousel.stories.tsx
- close #112 
- 모바일 터치 이벤트 추가 구현
- 기존에 존재했던 passive 가 true일 때 마우스 이벤트 오류 해결
- storybook에서 존재하던 key에러 해결
**오류** : ```Unable to preventDefault inside passive event listener invocation``` 
passive 속성이 true로 설정되면 브라우저는 해당 이벤트 리스너가 페이지 스크롤 성능을 향상시키기 위해 호출되는 것으로 간주하고, preventDefault를 호출할 수 없도록 한다.
일반적으로 스크롤 관련 이벤트 예를 들어 touchmove와 같은 이벤트 리스너에서 preventDefault를 호출하는 것은 
스크롤을 방지하고자 하는 목적인데 
브라우저는 성능 이슈를 방지하기 위해 "passive" 속성이 true로 설정된 경우에는 preventDefault를 허용하지 않는다고 한다.
코드에서는 passive 속성을 지정하지 않았지만 아래와 같은 이유로 문제가 생겨난다.
> passive 속성이 false인 경우에 touchstart, touchmove와 같은 이벤트가 발생하면 preventDefault를 이용하여 실제 이벤트 자체를 막을 수 있기 때문에, 브라우저는 scroll을 계속 할지 안할지를 매번 감시해야만 한다.
> 하지만, passive 속성이 true일 경우에는 preventDefault를 이용하여 scroll 이벤트를 막지 않겠다고 브라우저에게 이야기하는 것과 같다. 따라서, 이 룰을 어기면 브라우저는 가차없이 다음과 같은 에러를 던진다.
> 다행이 …
> refactor: Carousel 모바일 터치 이벤트 추가 구현

- src/common/components/ExtraInfo/index.tsx
- src/common/hooks/mutations/useLogout/index.ts
- src/constants/message.ts
- src/pages/register/components/RegisterForm/index.tsx
- src/pages/register/hooks/useEmailDuplicate.ts
- src/utils/isValid.ts
> refactor: 로그아웃 캐싱 제거, 회원가입 버그, ExtraInfo 가운데 정렬, 닉네임 정규표현식 문제 해결

- src/Router.tsx
- src/common/hooks/queries/useAllUsers/index.ts
- src/pages/account/components/PostsList/index.tsx
- src/pages/account/index.tsx
- src/pages/follow/components/FollowListItem/index.tsx
- src/pages/follow/components/FollowersList/index.tsx
- src/pages/follow/components/FollowingList/index.tsx
- src/pages/follow/index.tsx
- close #129 
- follow 페이지에 데이터를 navigate를 활용하여 전달했습니다. (get follows 또는 get follow api 없음)
- follow 페이지 내의 user 데이터는 getusers로 가져온 데이터를 filter 처리 하여 불러왔습니다.
> feat: followlist 구현

- src/Router.tsx
- close #160 
*디스코드 회의를 통해 일부 내용을 수정합니다.
- 라우터 단에서 user 정보를 통해 리다이렉트 여부를 결정합니다.
- 리다이렉트 use case는 다음과 같습니다.
1. 유저 정보와 관계 없이 이동할 수 있는 라우터
- Home Page
- Search Page
- Post Detail Page
- Follow Page
- Account Page(다른 유저 정보)
- Message Page
2. 유저 정보가 있을 때만 이동할 수 있는 라우터
- Account Page(내 정보)
- Account Edit Page
- Message Send Page
- Notification Page
- Update Password Page 
3. 유저 정보가 없을 때만 이동할 수 있는 라우터
- Login Page
- Logout Page
제가 놓친 부분이나 잘못 생각한 부분이 있다면 언제든 말씀해주세요!
그리고 추후 추가될 라우터는 케이스 별로 라우터에 추가해주시면 되겠습니다.
> refactor: 라우터 리다이렉트 구현

- src/pages/notification/components/NotificationList/Alarm.tsx
- src/pages/search/components/SearchResults/PostItem.tsx
- src/pages/search/components/SearchResults/UserItem.tsx
- src/pages/search/components/SearchResults/index.tsx
- close #162 
- 검색, 알림 페이지에서 `utils/jsonToData.ts`의 함수를 사용하는 것으로 변경했습니다.
- Avatar 크기를 줄였습니다.
- 페이지 이동 시 `useNavigate`를 사용하던 것에서 Link 태그 사용으로 변경했습니다.
- [[React] Link 컴포넌트와 useNavigate의 차이](https://velog.io/@ahn-sujin/React-Link-%EC%BB%B4%ED%8F%AC%EB%84%8C%ED%8A%B8%EC%99%80-useNavigate%EC%9D%98-%EC%B0%A8%EC%9D%B4)
> refactor: search notification

- src/common/components/Tab/TabItem.tsx
- src/pages/follow/index.tsx
- src/pages/moreUsers/components/UserList/index.tsx
- src/pages/moreUsers/index.tsx
- src/pages/search/components/SearchResults/index.tsx
- src/pages/search/index.tsx
- close #171 
- Tab 컴포넌트에 아이템 수를 작성할 수 있는 `subText`를 추가했습니다.
- Tab 컴포넌트를 사용하는 Search, MoreUsers, Follow 페이지에 `subText`를 추가했습니다.
> refactor: Tab 컴포넌트 subText 추가

- vercel.json
- close #178 
- 구현한 내용
- 배포 사이트에서 새로고침 시 404 에러가 발생하는 문제를 해결하기 위해 vercel.json을 추가했습니다.
[Legacy SPA Fallback](https://vercel.com/docs/projects/project-configuration#legacy-spa-fallback)
> fix: spa fallback 해결

- src/pages/postDetail/components/CommentListItem/index.tsx
- closed #181
- 댓글이 길어져도 wrap 되지 않도록 tailwindcss className을 추가합니다.
- `flex-1`
> fix: comment wrap 버그 수정

- src/common/components/AcordionButton/index.tsx
- src/common/components/ThemeButton/index.tsx
- src/common/components/Toast/ToastItem.tsx
- src/common/hooks/mutations/useUploadImage/index.tsx
- src/common/hooks/queries/useAllUsers/index.ts
- src/pages/accountEdit/components/EditAccountImages/index.tsx
- src/pages/follow/components/FollowersList/index.tsx
- src/pages/follow/components/FollowingList/index.tsx
- src/pages/search/components/SearchBar/index.tsx
- src/styles/global.css
- close #184 
- 계정 페이지 아바타의 크기가 맞지 않는 부분을 수정했습니다.
- 계정 변경 로직에 post를 invalidatequeries에 추가하여 계정을 수정한 이후 아바타 사진이 바로 리패치 되도록 하였습니다.
- 다크모드 시에 라이트 모드 일때와 동일한 스타일을 수정하였습니다.
> Fix: account page 수정, 다크모드 시 스타일 수정

- src/common/components/Avatar/index.tsx
- src/common/components/Layout/index.tsx
- src/pages/account/components/AccountImages/index.tsx
- src/pages/postDetail/components/CommentInput/index.tsx
- src/pages/postDetail/components/CommentListItem/index.tsx
- src/pages/postDetail/components/PostDetailComponent/index.tsx
- src/pages/postDetail/components/PostDetailUserInfo/index.tsx
- close #191 
- acordionButton과 다크모드 버튼 위치 변경 - 모바일 환경에서 너무 타이트하게 출력됨
- 댓글의 아바타 늘려지는 현상 해결
- 
- 게시글 상세 페이지의 아바타와 댓글의 아바타 클릭시 undefined와 자신의 account 페이지에 가고있지 않은 문제 해결
> refactor: 홈 버튼 위치 변경 및 댓글 문제 해결

- src/pages/messageSend/components/MessageSendList/index.tsx
- src/pages/search/components/SearchBar/index.tsx
- close #195 
- 검색 바, 메시지 송수신 페이지가 다크모드일 때 시각적으로 잘 보이지 않는 문제 해결
- 모바일 타이틀 문제는 웹이나 다른 환경에서는 잘 작동함 추후 다시 해결해야하는 문제 - 인스타 외부링크로 가는 특정한 상황에만 발생함
> refactor: 검색바, 메시지 송수신 다크모드 스타일링
