prgrms-fe-devcourse/FEDC5_Owhat_Byunghyun

src/components/common/Text/Text.variants.ts, src/components/common/Text/index.tsx, src/stories/Text.stories.tsx
close #15 
- Text Component variants 변수 타입 수정
- 겹치는 Text 컴포넌트 Props 속성과 HTML 속성 수정
=> Fix/#15 text component 수정

.prettierrc, src/components/common/Loading/Loading.variants.ts, src/components/common/Loading/index.tsx, src/stories/Loading.stories.tsx
- #11 
- 버튼, 화면 등에 사용할 spinner를 구현했습니다.
- css만을 이용하여 spinner를 구현했습니다.
- storybook에서 spinner의 굵기, 크기, 색상을 변경하여 확인할 수 있습니다.
- variants에 필요한 속성들을 알맞게 작성했는지 궁금합니다.
- stories 파일에서 argTypes에 className이외에 다른 값을 작성해주지 않았는데, 다른 값들을 추가해주지 않아도 되는 건지 확인부탁드립니다.
=> feat: Loading 컴포넌트 구현

src/common/components/Group/index.tsx, src/stories/Group.stories.tsx, src/styles/global.css, tailwind.config.js
- close #56 
- 디자인 통일성을 위해 기본 테마 수정 및 추가
- Group 컴포넌트 오타 수정
- [디자인시스템 참고자료](https://www.figma.com/file/X3TRPxPuSUZnjjyUXB01uh/Atom-%E2%80%94-Web-Design-System-(Community)?type=design&node-id=14-426&mode=design&t=UVBGpWC5uy7f037w-0)
- [Tailwind 공식문서 테마지정 참고자료](https://tailwindcss.com/docs/theme)
=> refactor: 기본 테마 수정

src/common/components/ExtraInfo/ExtraInfo.variants.ts, src/common/components/ExtraInfo/index.tsx, src/common/components/Input/Input.variants.ts, src/common/components/Text/Text.variants.ts, src/common/components/Text/index.tsx, src/stories/ExtraInfo.stories.tsx, src/stories/Text.stories.tsx, src/styles/global.css, tailwind.config.js
- close #58  
- tailwind.config, global.css 수정으로 인한 담당 컴포넌트 스타일 리팩토링을 작업함
- config 내 사용이 제대로 되지 않는 property 명 수정 (ex. radius, fontSize 내 base)
- global.css 내 text-black 전체 선택자로 이동, div/span/p 태그 설정 삭제
=> Refactor: 담당 component styles 리팩토링

.gitignore, package-lock.json, package.json, src/api/index.ts, src/utils/storage.ts
- close #86 
[axios 인스턴스 참고 자료](https://velog.io/@rudans987/axios-%EC%9D%B8%EC%8A%A4%ED%84%B4%EC%8A%A4-%EC%82%AC%EC%9A%A9%EB%B2%95)
[LocalStrage 예제](https://blog.banksalad.com/tech/typescript-local-storage/)
[axios 헤더 설정](https://velog.io/@kcj_dev96/axios-%EC%9D%B8%EC%8A%A4%ED%84%B4%EC%8A%A4-%EC%83%9D%EC%84%B1%EA%B3%BC-%ED%97%A4%EB%8D%94-%EC%84%A4%EC%A0%95)
> 과거엔 클라이언트 측에 정보를 저장할 때 쿠키를 주로 사용하곤 했습니다. 쿠키를 사용하는 게 데이터를 클라이언트 측에 저장할 수 있는 유일한 방법이었을 때는 이 방법이 타당했지만, 지금은modern storage APIs를 사용해 정보를 저장하는 걸 권장합니다. 모든 요청마다 쿠키가 함께 전송되기 때문에, (특히 mobile data connections에서) 성능이 떨어지는 원인이 될 수 있습니다. 정보를 클라이언트 측에 저장하려면 Modern APIs의 종류인 [웹 스토리지 API](https://developer.mozilla.org/ko/docs/Web/API/Web_Storage_API) (localStorage와 sessionStorage) 와 [IndexedDB](https://developer.mozilla.org/ko/docs/Web/API/IndexedDB …
=> build: axios 인스턴스 및 localStorage 구축

src/api/types/notificationTypes.ts, src/api/types/postTypes.ts, src/api/types/userTypes.ts, src/common/components/Alarm/index.tsx, src/stories/Alarm.stories.tsx
- close #62 
- API response type을 `src/api/types` 폴더에 세 분류로 파일을 나누어 작성했습니다.
- `COMMENT`, `FOLLOW`, `LIKE`, `MESSAGE`에 따라 내용이 달라지는 Alarm 컴포넌트를 구현했습니다.
- `username: User.fullName`
- `comment`, `follow`, `like`, `message`는 notificationType에 맞는 값이 API 응답으로 내려옵니다. 해당하는 데이터를 prop으로 넘길 수 있습니다. 
```javascript
// follow 제외하고 모두 string
comment: comment.post.title
follow: Follow
like: like.post.title
message: messageId
```
- 현재 prop에 `comment`, `follow`, `like`, `message`를 optional로 받고 있습니다. 각각의 type을 `AlarmProps`에 명시하기 위해 이처럼 구현했는데, notificationType이라는 하나의 prop으로 관리하는 것이 좋을까요?
- 결국은 한 문장으로 나타나는데 Text 컴포넌트를 여러 번 사용하고 있습니다. 개선할 수 있는 아이디어가 있다면 코멘트 부탁드려요!
- `types` 폴더 내에 있는 파일명이나 type 분류에 대한 의견이 있다면 나눠주세요!
=> feat: Alarm 컴포넌트 구현

src/api/types/userTypes.ts
- close #96  
- Usertypes 내 following, followers 타입 유니온으로 변경
- 추후 제네릭 타입으로 리팩토링 필요
=> hotfix: usertypes 내 following, followers 유니온으로 수정

src/api/types/postTypes.ts, src/api/types/userTypes.ts
- close #99 
- 실제 API 응답 type에 맞게 유니온 타입으로 변경했습니다.
=> fix: API response type union으로 변경

src/common/components/ArrowBackButton/index.tsx
- close #102 
- useLayout에서 필요한 뒤로가기 버튼 컴포넌트 구현
- useNavigate 사용
=> feat: ArrowBackButton 구현

src/common/components/Carousel/index.tsx, src/common/components/Carousel/useDragScroll.ts, src/pages/home/components/ChannelList/index.tsx
- close #123 
- 채널에 이미지를 위해 서버에서 기존에 존재하던 채널 데이터 삭제 후 description에 이미지 url 저장해서 다시 생성
- 채널의 description을 가지고 채널 로고 이미지 출력
- Carousel 이미지 드래그 문제 해결
=> refactor: OTT 플랫폼 로고 이미지 추가 및 Carousel  드래그 버그 수정

src/Router.tsx, src/api/message.ts, src/api/user.ts, src/common/hooks/queries/useMessageList/index.ts, src/common/hooks/queries/useOnlineUsers/index.ts, src/constants/queryKey.ts, src/pages/message/components/MessageList/Skeleton.tsx, src/pages/message/components/MessageList/index.tsx, src/pages/message/components/OnlineUsers/Skeleton.tsx, src/pages/message/components/OnlineUsers/index.tsx, src/pages/message/index.tsx, src/stories/pages/MessagePage.stories.tsx
- close #132 
- message page를 구현했습니다.
- message datail page는 추후 구현할 예정입니다.
- message list에 무한 스크롤 등의 기능이 필요하다면 추후 구현하도록 하겠습니다.
- online user list는 유저 수를 통제할 수 없어서 offline을 합한 전체 유저로 테스트를 작성해두었습니다.
=> fea: message page 구현

src/common/components/HomeButton/index.tsx, src/pages/home/index.tsx, src/pages/login/index.tsx, src/pages/register/index.tsx
- close #141 
- 로그인 페이지에서 홈 버튼 추가
=> refactor: 로그인 페이지 홈 버튼 구현

src/api/index.ts, src/api/user.ts, src/common/hooks/mutations/useLikeFromPost/index.ts, src/common/hooks/mutations/useLogin/index.tsx, src/common/hooks/mutations/useLogout/index.ts, src/pages/account/index.tsx, src/pages/home/components/ChannelList/index.tsx, src/pages/login/index.tsx
- close #145 
- axios에 토큰값을 동적으로 넣기 위한 인터셉터 추가 및 토스트 컴포넌트 추가
=> refactor: 로그인 후 authUser에 빈 토큰 값으로 가는 문제 해결

src/api/types/notificationTypes.ts
- close #151 
- 알람 request body 타입 property 백엔드 명세서와 맞췄습니다.
=> fix: notification request body 타입 수정

src/common/components/ArrowBackButton/index.tsx, src/common/components/Layout/index.tsx, src/common/components/NavigationBar/index.tsx
- close #154 
- ArrowBackButton에 있는 Icon 컴포넌트에 onClick이 등록되어있는 문제 해결
- 로그인 시 알람 표시 기능
- 로그인 시 마이페이지가 사용자 아바타로 변경되는 기능
- 쿼리 키 값으로 캐싱 데이터 가져오기를 수행하려고 했으나 로그인 이후 정상작동하다가 새로고침을 할 때 user키 값에
undefined가 고정으로 들어가는 문제로 인해 useQuery사용
[쿼리 키값 가져오기](https://tanstack.com/query/latest/docs/react/reference/QueryClient#queryclientgetquerydata)
- 이후 useQuery를 줄이는 방법을 계획해야 함
=> feat: 네비게이션 바에 로그인과 알람 표시 기능 구현 및 arrowback 수정

src/common/hooks/mutations/useLogin/index.tsx, src/pages/message/components/MessageList/index.tsx
- closed #163 
- 유저 인증 정보가 없을 때 fallback 문구와 함께 로그인 페이지로 이동할 수 있는 버튼을 제공합니다.
- 로그인 후 원래 머물러 있던 페이지로 되돌아옵니다.
=> refactor: message fallback

src/Router.tsx, src/pages/404/index.tsx, src/pages/message/components/OnlineUsers/index.tsx, src/pages/message/index.tsx
- closed #167
- fix: 영어 글자 수 초과 시 ellipsis를 적용합니다.
- feat: 404 page 생성합니다.
- feat: 유저 더보기 버튼을 추가했습니다.
=> feat: 유저 더보기 버튼 추가

src/Router.tsx, src/api/post.ts, src/common/components/HomeButton/index.tsx, src/common/components/NavigationBar/index.tsx, src/common/hooks/mutations/useCreatePost/index.ts, src/common/hooks/mutations/useDeleteComment/index.ts, src/common/hooks/mutations/useDeletePost/index.ts, src/common/hooks/mutations/useUploadPostImage/index.ts, src/pages/home/index.tsx, src/pages/message/index.tsx, src/pages/messageSend/index.tsx, src/pages/postCreate/components/UploadButton/index.tsx, src/pages/postCreate/hooks/useCreatePostForm.tsx, src/pages/postCreate/index.tsx, src/pages/postDetail/components/CommentListItem/index.tsx, src/pages/postDetail/components/PostDetailComponent/index.tsx, src/pages/postDetail/components/PostDetailUserInfo/index.tsx, src/pages/postDetail/index.tsx
- close #169 
- 스타일 및 오타 수정
- 게시글 작성 완료시 해당되는 채널의 홈페이지로 이동
- 게시글 작성 시 새로고침하면 router에러 해결 -> **useSuspenseQuery를 쓰이는 페이지는 무조건 suspense를 등록해줘야한다.**
=> refactor: 스타일, 오타 수정 및 router suspense 추가

src/common/components/AcordionButton/index.tsx, src/common/components/Button/index.tsx, src/common/components/Layout/index.tsx, src/common/components/ThemeButton/index.tsx, src/common/hooks/mutations/useCreateComment/index.ts, src/common/hooks/mutations/useDeleteComment/index.ts, src/common/hooks/mutations/useDeletePost/index.ts, src/common/hooks/mutations/useLikeFromPost/index.ts, src/common/hooks/queries/useNotificationList/index.ts, src/pages/home/components/FeedItem/index.tsx, src/pages/home/components/PostCreateButton/index.tsx, src/pages/home/index.tsx, src/pages/postDetail/index.tsx
- close #175 
- 댓글 작성 후 메인 페이지를 갔을 때 댓글 갯수가 최산화가 안되는 문제 해결
- 글쓰기 버튼과 다크모드 버튼 통합
- 만약 메인페이지가 아니라면 다크모드 버튼만 렌더링
- 캐싱문제 해결
=> refactor: 버튼 통합 및 캐싱 문제 해결, 게시글 삭제시 해당 채널 홈으로 이동

src/Router.tsx, src/common/hooks/mutations/useCreatePost/index.ts, src/pages/postDetail/components/CommentInput/index.tsx, src/pages/postDetail/components/MoreButton/index.tsx, src/pages/search/components/SearchBar/index.tsx
- close #187 
- 댓글 입력 바, 검색 바 스타일링 수정
- 게시글 작성 라우터 수정
=> refactor: 게시글 작성 버그 해결 및 댓글, 검색바 스타일 깨짐 해결

src/common/components/Layout/index.tsx, src/pages/postDetail/components/CommentInput/index.tsx, src/pages/search/components/SearchBar/index.tsx
- close #189 
- 네비게이션 바와 비슷하게 스타일을 변경함
- input요소에 grow대신 w-full로 해결
=> refactor: 360px이하 스타일 깨짐 문제 해결
